### ISSUE TITLE
[Question] How to utilize this library

### ISSUE THREAD

**Issue by ZomViD** [EmilSodergren/rust-tuya-mqtt#183]
Hello, 

I would like to develop with local Tuya and get notifications when a Tuya Camera detected motions.
After many searches on the Internet with the combination of Rust, local Tuya, MQTT, Tuya Camera, I only got something vague. 

I do saw the MQTT broker + rust-tuya-mqtt solution, but I don't understand what data model I need to prepare or to deal with! 
I just don't have a clue where to start with. (I've already extracted the keys needed)
Could you please enlighten me on how to get notifications with local Tuya and a Tuya camera?

Thanks in advance!

**Comment by EmilSodergren** [comment]
So, first of all this is an application. It uses the library rust-tuyapi. This application is very limited in its functionality and you will have to extend it, possibly quite a bit, to support a camera. Also, rust-tuyapi only connects to the device when you send data to it, it receives the response and then disconnects. There is no way for the device to initiate a connection.

I only use some version 3.3 sockets, which currently is the highest version of the Tuya api supported by rust-tuyapi. I have had on my todo list to try to implement version 3.4 and 3.5; which, if you have bought your camera recently, is probably what you need. 

There is no way that I could squeeze maintenance of this into my life right now. Your best bet would be to implement something on top of [TinyTuya](https://github.com/jasonacox/tinytuya) or some other implementation.

If you have an idea and would like to contribute I'll gladly take a look at it.

**Comment by ZomViD** [comment]
Many thanks for the detailed reply and sharing your knowledge! I do appreciate it!

> "if you have bought your camera recently, is probably what you need."

For the camera, it's an outdated model which only has 2.4GHz WiFi-5 connection, so it might using some older protocols.
Is this meant there is no way to let these older devices to notify a local App? Or I've to use the Tuya cloud to get a notification?

> "rust-tuyapi only connects to the device when you send data to it, it receives the response and then disconnects."

What about to use a loop to poll the status, will it get the notification?

> "If you have an idea and would like to contribute I'll gladly take a look at it."

After some quick readings on the TinyTuya project, It seems that they could somehow receive a broadcast from the local Tuya device. If I can get the broadcast, then the things left seem to be easier? 
Since your Tuya projects are of the most complete among Rust ecosystem. 
My current thought is that I would like to try Go/Python to see if they have some more complete solution(s), then make a prototype App. After a more robust understanding of the whole IOT/MQTT/Tuya/local Tuya things, I will try to re-write the prototype App in Rust and I would love to contribute the things I knew.
But I can't guarantee it will happen very soon!



Thanks again! Do have a great weekend!
